- name: creating catalogue  
  hosts: catalogue
  become: yes
  tasks:
  - name:  disableing old  nodejs ebnable new nodejs 
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name:  Install NodeJS
    ansible.builtin.dnf: 
      name: httpd
      state: present

  - name: create roboshop user 
    ansible.builtin.user:
      name: roboshop
  
  - name: creating app directory 
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download the application 
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  
  - name: unzipping 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      
