- name: installing rabbit mq 
  hosts: rabbitmq
  become: yes 
  tasks:
    - name: creating rabbit repo
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: configure repo for rabbit mq
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: install rabbit mq
      ansible.builtin.dnf:
        name: rabbitmq-server 
        state: present 

    - name: enable rabbitmq-server 
      ansible.builtin.service:
        name: rabbitmq-server
        state: restarted
        enable: yes

    - name: user adding 
      ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

    - name: set permissions
      ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
       

