- name: redis installation 
  hosts: redis
  become: yes
  tasks:
    - name: inistiatting  redis repo file 
      ansible.builtin.command: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    
    - name: enable redis
      ansible.builtin.service:
        name: redis-server
        enabled: yes

    - name: Installing Redis
      ansible.builtin.service:
        name: redis
        state: present

    - name: allow remote connection 
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: start redis
      ansible.builtin.service:
        name: redis
        enabled: yes
        state: start
